### ISSUE TITLE
About the experiment results

### ISSUE THREAD

**Issue by Baymine** [lixiaotong97/DSU#2]
Did you use the best  results (show in the output log) as your final results? If not, would you please tell me how did you  get the results reported in the paper? Thank you.

**Comment by lixiaotong97** [comment]
We use the results of the last checkpoint by default. Considering the dataset is relatively small and thus suffers fluctuations, such as PACS, we show the results with the best performances. 
There can be some fluctuations in performances due to the different environments, the relative improvement should be significant regardless of these.

Best of wishes.
