### ISSUE TITLE
Could not implement the paper's results of semantic segmentation task

### ISSUE THREAD

**Issue by jiangzhengkai** [lixiaotong97/DSU#6]
Hi, I run the code to implement semantic segmentation results of GTA5->Cityscapes. The baseline result is 38.8, which is 1.8 higher than you report in the paper. The DSU result is 41.05, which is 2.0 lower than you report in the paper.

I follow the code and run the experiment on 4 V100.

baseline detail:
![image](https://user-images.githubusercontent.com/19780166/188272747-345cd7ea-8b31-444a-9aac-95b7fe914b0e.png)

DSU detail:
![image](https://user-images.githubusercontent.com/19780166/188272776-5b009121-bc95-4c59-9f58-71cc0e3edeee.png)

I want to know how you report the result in the paper, whether it is a mean way or max way?

**Comment by lixiaotong97** [comment]
Hi, Thanks for your interest in our work!

The segmentation experiment adopts the result of last checkpoint to report, which follows the setup of the repo [pAdain](https://github.com/onuriel/PermutedAdaIN/tree/main/FADA). 
(Our corresponding checkpoints and logs have been provides in [link](https://drive.google.com/drive/folders/1Pn60zo9wAZ656KiuKeqtnkRZNQgbnqcM?usp=sharing). )

1. It would be some fluctuations due to the user environment, you could try to change seeds and run more times. 
2. Besides, some fluctuations would come out in the last checkpoints and similar case also occurs in pAdain [issue](https://github.com/onuriel/PermutedAdaIN/issues/2).

Best regards.
